trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -m venv .env
    source .env/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pytest
  displayName: 'Build and Test'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
  displayName: 'Publish Artifact'


